<?php

namespace Container2rAlACv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Console_Command_StimulusComponentDebug_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.console.command.stimulus_component_debug.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.console.command.stimulus_component_debug.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('debug:twig-component', [], 'Display current components and them usages for an application', false, function () use ($container): \Symfony\UX\TwigComponent\Command\ComponentDebugCommand {
            return ($container->privates['console.command.stimulus_component_debug'] ?? $container->load('getConsole_Command_StimulusComponentDebugService'));
        });
    }
}
