<?php

namespace Container2rAlACv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_StimulusComponentDebugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.command.stimulus_component_debug' shared service.
     *
     * @return \Symfony\UX\TwigComponent\Command\ComponentDebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-twig-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ComponentDebugCommand.php';

        $container->privates['console.command.stimulus_component_debug'] = $instance = new \Symfony\UX\TwigComponent\Command\ComponentDebugCommand((\dirname(__DIR__, 4).'/templates'), ($container->privates['ux.twig_component.component_factory'] ?? $container->load('getUx_TwigComponent_ComponentFactoryService')), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), new RewindableGenerator(function () use ($container) {
            return new \EmptyIterator();
        }, 0));

        $instance->setName('debug:twig-component');
        $instance->setDescription('Display current components and them usages for an application');

        return $instance;
    }
}
